# fly.toml app configuration file generated for clusterms on 2025-04-02T23:57:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clusterms'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
